services:
  postgres_local:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres_user  #/run/secrets/pg_user
      POSTGRES_PASSWORD: postgres_password  #/run/secrets/pg_password
      POSTGRES_DB: pg_db_name #/run/secrets/pg_db
    ports:
      - "5432:5432"
    volumes:
      - .:/sufle/learning/app
    secrets:
      - pg_password
      - pg_user 
      - pg_db

  django_local:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/sufle/learning/app 
    depends_on:
      - postgres_local
  
secrets:
  pg_user:
      file: ./secrets/pg_user.txt
  pg_password:
      file: ./secrets/pg_password.txt
  pg_db:
      file: ./secrets/pg_db.txt


